##
# Makefile to create documentation from SICLA Admin Project
# AAFR
# 17 agosto 2013
##

all: doc

doc: clean
	doxygen monitoreo.dox
	

clean:
	
	rm -rf rtf/
	rm -rf html/
	rm -rf latex/
	
	rm -rf problemas.txt
